FROM oven/bun:1 as base
WORKDIR /app

# Copy everything
COPY . .

# Install dependencies
RUN bun install

# Build shared packages and server
RUN bun run build --filter=server...

WORKDIR /app/apps/server
EXPOSE 8080

CMD ["bun", "run", "src/index.ts"]