[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build --filter=server..."]

[start]
cmd = "cd apps/server && bun run src/index.ts"

[variables]
PORT = "8080"